### ISSUE TITLE
Erroneous html tags

### ISSUE THREAD

**Issue by fsimonjetz** [chardmeier/parcor-full#1]
Hello there,
I just noticed that there are extra HTML tags (\<html\> and \<body\>) in the following three files which broke a Python module I made for importing MMAX projects:

parcor-full/corpus/news/EN/Markables/03_coref_level.xml
parcor-full/corpus/news/EN/Markables/20_coref_level.xml
parcor-full/corpus/news/EN/Markables/25_coref_level.xml

While this doesn't seem to be an issue when opening the files in MMAX, I think those tags are not supposed to be there.

**Comment by chardmeier** [comment]
Hello! The tags were definitely not supposed to be there. I've removed them and checked that there are no html tags in the other XML files. Thanks for bringing this to our attention!
